-- Exam portions + Half Yearly timetable (2026-27) for the app's "Periodic Test" page.
-- Generated from web/schoolappupdate/*.xlsx (Annual Portion Grade 1-8, HALF YEARLY EXAM TT).
--
-- 1. Adds `exam` ('PT-1' | 'Half Yearly' | 'PT-2' | 'Annual') and `grade` (1-10) to the
--    periodic_test_* tables. Existing rows are PT-1 and their `classesID` already held the
--    GRADE NUMBER (1 = Grade 1 ...), so `grade` is copied from it. The API now matches a
--    student by grade (from the class name "Grade 1 A" -> 1), so every section sees its grade.
-- 2. Replaces the syllabus of Grades 1-8 (all four exams) with the Annual Portion files.
-- 3. Replaces the Half Yearly timetable for Grades 1-10.
-- Safe to re-run (MariaDB IF NOT EXISTS + delete-then-insert).

ALTER TABLE `periodic_test_schedule`
    ADD COLUMN IF NOT EXISTS `exam` VARCHAR(30) NOT NULL DEFAULT 'PT-1',
    ADD COLUMN IF NOT EXISTS `grade` TINYINT UNSIGNED NULL;
ALTER TABLE `periodic_test_syllabus`
    ADD COLUMN IF NOT EXISTS `exam` VARCHAR(30) NOT NULL DEFAULT 'PT-1',
    ADD COLUMN IF NOT EXISTS `grade` TINYINT UNSIGNED NULL;

UPDATE `periodic_test_schedule` SET `grade` = `classesID` WHERE `grade` IS NULL;
UPDATE `periodic_test_syllabus` SET `grade` = `classesID` WHERE `grade` IS NULL;

ALTER TABLE `periodic_test_schedule` ADD INDEX IF NOT EXISTS `idx_grade_exam` (`grade`, `exam`);
ALTER TABLE `periodic_test_syllabus` ADD INDEX IF NOT EXISTS `idx_grade_exam` (`grade`, `exam`);

-- ---- Syllabus: Grades 1-8, PT-1 / Half Yearly / PT-2 / Annual ----------------------
DELETE FROM `periodic_test_syllabus` WHERE `grade` BETWEEN 1 AND 8;

-- Grade 1
INSERT INTO `periodic_test_syllabus` (`classesID`, `grade`, `exam`, `subject`, `syllabus`) VALUES
(1, 1, 'PT-1', 'ENGLISH', 'Lesson Number- 1, Poem - All of Me,\nGrammar- Lesson No.-1\nComposition-My Self.'),
(1, 1, 'PT-1', 'HINDI', 'अ, आ, इ, ई की मात्राओं के शब्द, वाक्य और इन्हीं पाठों पर आधारित व्याकरण |'),
(1, 1, 'PT-1', 'MARATHI', 'स्वर – अ ते अः'),
(1, 1, 'PT-1', 'MATHS', 'Lesson No.-1 & 2'),
(1, 1, 'PT-1', 'EVS', 'Lesson No.-1 to 3'),
(1, 1, 'PT-1', 'ART', '1. House,\n2. Umbrella'),
(1, 1, 'PT-1', 'COMPUTER', 'Lesson No.- 1'),
(1, 1, 'PT-1', 'G.K.', 'Page No.-1 to 11'),
(1, 1, 'Half Yearly', 'ENGLISH', 'Lesson No.- 2 to 5, Poems-At School &\nMr. Caterpillar\nGrammar- Lesson No.- 1 to 8 Composition- My School.\nPicture Comprehension'),
(1, 1, 'Half Yearly', 'HINDI', 'उ से औ की मात्राओं के शब्द व वाक्य और इन्हीं पाठों पर आधारित व्याकरण |'),
(1, 1, 'Half Yearly', 'MARATHI', 'व्यंजन (क ते म)\nOral – कविता बाहुली'),
(1, 1, 'Half Yearly', 'MATHS', 'Lesson No.- 3 to 7\nTables - 2 to 5'),
(1, 1, 'Half Yearly', 'EVS', 'Lesson No.- 4 to 11'),
(1, 1, 'Half Yearly', 'ART', '1. Fish in water,\n2. Butterfly,\n3. Lady Bug,\n4. Rabbit (Bunny)'),
(1, 1, 'Half Yearly', 'COMPUTER', 'Lesson No.-2 & 3'),
(1, 1, 'Half Yearly', 'G.K.', 'Page No.-12 to 32'),
(1, 1, 'PT-2', 'ENGLISH', 'Lesson No.- 1 , Poem - Child Song,\nGrammar- Lesson No.-1 to 9\nComposition - Save Trees.\nPicture Comprehension'),
(1, 1, 'PT-2', 'HINDI', 'अं, अः, चंद्रबिंदु की मात्रा,\nसंयुक्त व्यंजन,\nपशु–पक्षी जगत,\nशरीर के अंग |'),
(1, 1, 'PT-2', 'MARATHI', 'व्यंजन (य ते ज्ञ)\nअंक – (१ ते ५)'),
(1, 1, 'PT-2', 'MATHS', 'Lesson No.-1 & 2'),
(1, 1, 'PT-2', 'EVS', 'Lesson No.-1 to3'),
(1, 1, 'PT-2', 'ART', '1. My Favourite Vehicle ,\n2. Christmas Tree ,\n3. Fruit Basket ,\n4. Flower Garden'),
(1, 1, 'PT-2', 'COMPUTER', 'Lesson No.- 4'),
(1, 1, 'PT-2', 'G.K.', 'Page No.-33 to 44'),
(1, 1, 'Annual', 'ENGLISH', 'Lesson No.- 2 to 4, Poems- Rainbow &\nMy Big Fat Cat.\nGrammar- Lesson No.- 1 to15\nComposition - My Best Friend.\nPicture Comprehension'),
(1, 1, 'Annual', 'HINDI', 'पाठ ५ से १० और इन पाठों पर आधारित व्याकरण, अनुच्छेद लेखन |'),
(1, 1, 'Annual', 'MARATHI', 'व्यंजन – (क ते ज्ञ)\nअंक – (६ ते १०)\nOral – कविता (चांदोबा, चांदोबा)'),
(1, 1, 'Annual', 'MATHS', 'Lesson No.-3 to 7\nTables -6 to 10'),
(1, 1, 'Annual', 'EVS', 'Lesson No.-4 to 9'),
(1, 1, 'Annual', 'ART', '1. Kite ,\n2. Hot Air Ballon ,\n3. Cartoon ,\n4. Lotus'),
(1, 1, 'Annual', 'COMPUTER', 'Lesson No.-5 & 6'),
(1, 1, 'Annual', 'G.K.', 'Page No.-45 to 56');

-- Grade 2
INSERT INTO `periodic_test_syllabus` (`classesID`, `grade`, `exam`, `subject`, `syllabus`) VALUES
(2, 2, 'PT-1', 'ENGLISH', 'Lesson No.-1\nPoem- How they Sleep\nGrammar Lesson No.- 1 & 2\nComposition- My pet cat.'),
(2, 2, 'PT-1', 'HINDI', 'पाठ-१,२ और इन पाठ पर आधारित व्याकरण और जो कार्य कॉपी पर करवाया गया है ।'),
(2, 2, 'PT-1', 'MARATHI', 'पाठ-१,३,४\nपाठावर आधारित व्याकरण'),
(2, 2, 'PT-1', 'MATHS', 'Lesson No.-1 & 2'),
(2, 2, 'PT-1', 'EVS', 'Lesson No.-1 to 3'),
(2, 2, 'PT-1', 'ART', '1. Rainbow\n2. Parrot'),
(2, 2, 'PT-1', 'COMPUTER', 'Lesson No.-1'),
(2, 2, 'PT-1', 'G.K.', 'Page No.\'s - 1 to 11'),
(2, 2, 'Half Yearly', 'ENGLISH', 'Lesson No.- 2 to 5\nPoems-A Worm in my Pocket &\nThe Swings.\nGrammar- Lesson No.-1 to 8.\nComposition- My favourite season.'),
(2, 2, 'Half Yearly', 'HINDI', 'पाठ - ३ से ७\nव्याकरण-पाठ १ से ७ पाठ पर आधारित व्याकरण और जो व्याकरण कॉपी में करवाया है ।'),
(2, 2, 'Half Yearly', 'MARATHI', 'पाठ- ५ ते १ १\nव्याकरण - वचन ,लिंग,\nअंक १- २0 निबंध'),
(2, 2, 'Half Yearly', 'MATHS', 'Lesson No.- 3 to 8'),
(2, 2, 'Half Yearly', 'EVS', 'Lesson No.- 4 to 11'),
(2, 2, 'Half Yearly', 'ART', '1. Butterfly in Garden\n2. Lady Bug\n3. Fruit Basket\n4. Flamingo'),
(2, 2, 'Half Yearly', 'COMPUTER', 'Lesson No.- 2 to 4'),
(2, 2, 'Half Yearly', 'G.K.', 'Page No.\'s - 12 to 31'),
(2, 2, 'PT-2', 'ENGLISH', 'Lesson No.- 1\nPoem -The Growing River.\nGrammar : Lesson No.- 1 to 11.\nComposition- Importance of Trees.'),
(2, 2, 'PT-2', 'HINDI', 'पाठ -८,९ और इन पाठ पर आधारित व्याकरण और जो कार्य कॉपी पर करवाया गया है ।'),
(2, 2, 'PT-2', 'MARATHI', 'पाठ- १२ ते १५\nसोळाखडी \' क \' ते \' न \'\nवचन लिंग अंक २१- ३0'),
(2, 2, 'PT-2', 'MATHS', 'Lesson No.- 1 & 2'),
(2, 2, 'PT-2', 'EVS', 'Lesson No.-1 to 3'),
(2, 2, 'PT-2', 'ART', '1. Flower Pot\n2. Cartoon\n3. Peacock\n4. My Favourite Vehicle'),
(2, 2, 'PT-2', 'COMPUTER', 'Lesson No.- 5'),
(2, 2, 'PT-2', 'G.K.', 'Page No.\'s - 34 to 39'),
(2, 2, 'Annual', 'ENGLISH', 'Lesson No.- 2 to 4\nPoems- What makes you Laugh?\n& Frogs at School\nGrammar : Lesson No.- 1 to 16\nComposition- A picnic with my Family.\nStory writing.'),
(2, 2, 'Annual', 'HINDI', 'पाठ -१0 से १४\nव्याकरण -पाठ ८ से १४ पाठ पर आधारित व्याकरण और जो व्याकरण कॉपी में करवाया है ।'),
(2, 2, 'Annual', 'MARATHI', 'पाठ- १६ ते २१\nपाठावर आधारित व्याकरण\nअंक १- ३0 निबंध'),
(2, 2, 'Annual', 'MATHS', 'Lesson No.- 3 to 6'),
(2, 2, 'Annual', 'EVS', 'Lesson No.- 4 to 10'),
(2, 2, 'Annual', 'ART', '1. Boat Scenery\n2. Under Water Scenery\n3. Lotus\n4. Madhubani Art'),
(2, 2, 'Annual', 'COMPUTER', 'Lesson No.- 6 to 8'),
(2, 2, 'Annual', 'G.K.', 'Page No.\'s - 43 to 60');

-- Grade 3
INSERT INTO `periodic_test_syllabus` (`classesID`, `grade`, `exam`, `subject`, `syllabus`) VALUES
(3, 3, 'PT-1', 'ENGLISH', 'Lesson No.-1 & 2; Poem: I meant to do my work;\nGrammar Lesson No.-1 to 4.\nWriting skills- Refer to the Notebook.'),
(3, 3, 'PT-1', 'HINDI', 'पाठ १-२ और पाठो पर आधारित व्याकरण और जो व्याकरण कॉपी मे करवाया गया है ।'),
(3, 3, 'PT-1', 'MARATHI', 'पाठ क्र.१ ते ३. व्याकरण- पाठावर आधारित.'),
(3, 3, 'PT-1', 'MATHS', 'Lesson No.-1 & 2'),
(3, 3, 'PT-1', 'SCIENCE', 'Lesson No.-1 & 2'),
(3, 3, 'PT-1', 'SOCIAL', 'Lesson No.-1 & 3'),
(3, 3, 'PT-1', 'ART', '1. Warli Art\n2. Underwater Scenery'),
(3, 3, 'PT-1', 'COMPUTER', 'Lesson No.-1'),
(3, 3, 'PT-1', 'G.K.', 'Page No. - 1 to 12'),
(3, 3, 'Half Yearly', 'ENGLISH', 'Lesson No.-3 to 5 Poems: Song of the Engine & Homes;\nGrammar Lesson No.- 1 to 8.\nWriting skills- Refer to the Notebook.'),
(3, 3, 'Half Yearly', 'HINDI', 'पाठ -३ से ७ व्याकरण-पाठ १ से ७ पाठ पर आधारित व्याकरण और जो व्याकरण कॉपी में करवाया है ।'),
(3, 3, 'Half Yearly', 'MARATHI', 'पाठ क्र.४ ते ७ , व्याकरण-पाठ १ ते ७ पाठावर आधारित व्याकरण. अंक १ ते २० (निबंध)'),
(3, 3, 'Half Yearly', 'MATHS', 'Lesson No.- 3 to 6'),
(3, 3, 'Half Yearly', 'SCIENCE', 'Lesson No.- 3 to 7'),
(3, 3, 'Half Yearly', 'SOCIAL', 'Lesson No.- 4 to 10'),
(3, 3, 'Half Yearly', 'ART', '1. Boho Art\n2. Flower Pot\n3. Butterfly Garden\n4. Lady Bug'),
(3, 3, 'Half Yearly', 'COMPUTER', 'Lesson No.-2 & 3'),
(3, 3, 'Half Yearly', 'G.K.', 'Page No. -13 to 28'),
(3, 3, 'PT-2', 'ENGLISH', 'Lesson No.-1 & 2; Poems: Good Books;\nGrammar Lesson No.-1 to 12.\nWriting skills-Refer to the Notebook.'),
(3, 3, 'PT-2', 'HINDI', 'पाठ ८,९ और पाठो पर आधारित व्याकरण और जो कार्य कॉपी मे करवाया गया है ।'),
(3, 3, 'PT-2', 'MARATHI', 'पाठ क्र.८ ते १0 , व्याकरण- पाठावर आधारित.'),
(3, 3, 'PT-2', 'MATHS', 'Lesson No.- 1 & 2'),
(3, 3, 'PT-2', 'SCIENCE', 'Lesson No.- 1 & 2'),
(3, 3, 'PT-2', 'SOCIAL', 'Lesson No.-1 & 2'),
(3, 3, 'PT-2', 'ART', '1. Deer\n2. Fruit Basket\n3. Lotus\n4. Flamingo'),
(3, 3, 'PT-2', 'COMPUTER', 'Lesson No.- 4 & 5'),
(3, 3, 'PT-2', 'G.K.', 'Page No. - 29 to 44'),
(3, 3, 'Annual', 'ENGLISH', 'Lesson No.-3 to 5; Poems: Sea Treasures & Bless the Farmers;\nGrammar Lesson No.- 1 to 16.\nWriting skills- Refer to the Notebook.'),
(3, 3, 'Annual', 'HINDI', 'पाठ - १0 से १४ व्याकरण -पाठ ८ से १४ पाठ पर आधारित व्याकरण और जो व्याकरण कॉपी में करवाया है ।'),
(3, 3, 'Annual', 'MARATHI', 'पाठ क्र.११ ते १४, व्याकरण- पाठ ८ ते १४ पाठावर आधारित व्याकरण. अंक २१ ते ४0 (निबंध)'),
(3, 3, 'Annual', 'MATHS', 'Lesson No.- 3 to 6'),
(3, 3, 'Annual', 'SCIENCE', 'Lesson No.- 3 to 7'),
(3, 3, 'Annual', 'SOCIAL', 'Lesson No.- 3 to 7'),
(3, 3, 'Annual', 'ART', '1. 2D Design\n2. Madhubani Art\n3. Boat Scenery\n4. Light House'),
(3, 3, 'Annual', 'COMPUTER', 'Lesson No.- 6 & 7'),
(3, 3, 'Annual', 'G.K.', 'Page No.- 45 to 63');

-- Grade 4
INSERT INTO `periodic_test_syllabus` (`classesID`, `grade`, `exam`, `subject`, `syllabus`) VALUES
(4, 4, 'PT-1', 'ENGLISH', 'Lesson No.-1 and 2\nPoem: Topsy Turvy Land\nGrammar: Lesson No.- 1 to 3, Writing Skills- Refer to the Notebook.'),
(4, 4, 'PT-1', 'HINDI', 'पाठ-१,२ ;\nव्याकरण-पाठ पर आधारित व्याकरण\nऔर कापी में कार्य करवाया गया है।'),
(4, 4, 'PT-1', 'MARATHI', 'पाठ-१ ते ४; व्याकरण- पाठ :१,२,३,४\nपाठावर आधारित व्याकरण वहीत जे लिहिले आहे ते.'),
(4, 4, 'PT-1', 'SANSKRIT', 'पाठ १,२ ; पाठ-१ और पाठ २\nइन पाठों पर आधारित व्याकरण'),
(4, 4, 'PT-1', 'MATHS', 'Lesson No.-1 & 2'),
(4, 4, 'PT-1', 'SCIENCE', 'Lesson No.-1 & 2'),
(4, 4, 'PT-1', 'SOCIAL', 'Lesson No.-1 to 3'),
(4, 4, 'PT-1', 'ART', '1. Pot Design\n2. Animal'),
(4, 4, 'PT-1', 'COMPUTER', 'Lesson No.- 1'),
(4, 4, 'PT-1', 'G.K.', 'Page No.- 1 to 6'),
(4, 4, 'Half Yearly', 'ENGLISH', 'Lesson No.-3 to 5\nPoems: Choosing Their Names & The Tease\nGrammar: Lesson No.- 1 to 8, Writing Skills- Refer to the Notebook.'),
(4, 4, 'Half Yearly', 'HINDI', 'पाठ-३ से ७;\nव्याकरण -पाठ-१ से ७ तक पाठों पर आधारित व्याकरण\nऔर जो कापी में कार्य करवाया गया है।'),
(4, 4, 'Half Yearly', 'MARATHI', 'पाठ-४ ते ७; व्याकरण- पाठ १ ते ७\nपाठवर आधारित व्याकरण वहीतील कार्य.'),
(4, 4, 'Half Yearly', 'SANSKRIT', 'पाठ १ ते ६ ; पाठ-१ से ६ तक\nपाठों पर आधारित व्याकरण\nसंख्या १ से २० तक अंको और अक्षरों में'),
(4, 4, 'Half Yearly', 'MATHS', 'Lesson No.-3 to 7'),
(4, 4, 'Half Yearly', 'SCIENCE', 'Lesson No.-3 to 7'),
(4, 4, 'Half Yearly', 'SOCIAL', 'Lesson No.-5 to 9 (4 Activity)'),
(4, 4, 'Half Yearly', 'ART', '1. Thumb Printing\n2. Flag (butterfly)\n3. Rakhi Drawing & Decorations,\n4. Ganesha'),
(4, 4, 'Half Yearly', 'COMPUTER', 'Lesson No.- 2 to 4'),
(4, 4, 'Half Yearly', 'G.K.', 'Page No.- 7 to 23'),
(4, 4, 'PT-2', 'ENGLISH', 'Lesson No.-1 and 2 ; Poem: Trees\nGrammar: Lesson No.- 1 to 12, Writing Skills-Refer to the Notebook.'),
(4, 4, 'PT-2', 'HINDI', 'पाठ-८,९ ;\nव्याकरण -पाठ-८,९ पाठ पर आधारित व्याकरण\nऔर जो कापी में कार्य करवाया गया है।'),
(4, 4, 'PT-2', 'MARATHI', 'पाठ-८,९ ; व्याकरण- पाठ :८,९\nपाठावर आधारित वहीतील कार्य.'),
(4, 4, 'PT-2', 'SANSKRIT', 'पाठ ७, ८ ; पाठ-१ और पाठ ८\nपाठों पर आधारित व्याकरण\nसंख्या १ से २० तक अंको और अक्षरों में'),
(4, 4, 'PT-2', 'MATHS', 'Lesson No.-1 & 2'),
(4, 4, 'PT-2', 'SCIENCE', 'Lesson No.-1 & 2'),
(4, 4, 'PT-2', 'SOCIAL', 'Lesson No.-1 to 3'),
(4, 4, 'PT-2', 'ART', '1. Sunset\n2. Any bird\n3. Dolphin'),
(4, 4, 'PT-2', 'COMPUTER', 'Lesson No.- 5 & 6'),
(4, 4, 'PT-2', 'G.K.', 'Page No.- 24 to 33'),
(4, 4, 'Annual', 'ENGLISH', 'Lesson No.-3 to 5; Poems: One Look, The Rum Tum Tugger\nGrammar: Lesson No.- 1 to 17, Writing Skills- Refer to the Notebook.'),
(4, 4, 'Annual', 'HINDI', 'पाठ-१0 से १४ ; व्याकरण- पाठ-८ से १४ तक\nपाठों पर आधारित व्याकरण\nऔर जो कापी में कार्य करवाया गया है।'),
(4, 4, 'Annual', 'MARATHI', 'पाठ-१० ते १४ ; व्याकरण- पाठ:८ ते १४\nपाठावर आधारित व्याकरण वहीतील कार्य.'),
(4, 4, 'Annual', 'SANSKRIT', 'पाठ ७ ते १३ ; पाठ-१से १३ तक\nपाठों पर आधारित व्याकरण\nसंख्या १ से २० तक अंको और अक्षरों में'),
(4, 4, 'Annual', 'MATHS', 'Lesson No.-3 to 7'),
(4, 4, 'Annual', 'SCIENCE', 'Lesson No.-3 to 6'),
(4, 4, 'Annual', 'SOCIAL', 'Lesson No.-5 to 10 (4 Activity)'),
(4, 4, 'Annual', 'ART', '1. Diya\n2. Lantern\n3. Rangoli\n4. X-mass Tree\n5. Poster Save Earth'),
(4, 4, 'Annual', 'COMPUTER', 'Lesson No.- 7 to 9'),
(4, 4, 'Annual', 'G.K.', 'Page No.- 34 to 50');

-- Grade 5
INSERT INTO `periodic_test_syllabus` (`classesID`, `grade`, `exam`, `subject`, `syllabus`) VALUES
(5, 5, 'PT-1', 'ENGLISH', 'Lesson No.- 1 & 2\nPoems- Pocket Full of Sympathy. Grammar & Writing skills- Refer to the Notebook.'),
(5, 5, 'PT-1', 'HINDI', 'पाठ -१, २ और पाठ पर आधारित व्याकरण और जो कॉपी पर करवाया है ।'),
(5, 5, 'PT-1', 'MARATHI', 'पाठ क्र. -१,२,३ पाठावर आधारित व्याकरण'),
(5, 5, 'PT-1', 'SANSKRIT', 'पाठ: १, पाठ: २ - व्याकरण - पाठ: १ और पाठ: २ . इन पाठों पर आधारित व्याकरण'),
(5, 5, 'PT-1', 'MATHS', 'Lesson No.- 1 & 2'),
(5, 5, 'PT-1', 'SCIENCE', 'Lesson No.- 1 & 2'),
(5, 5, 'PT-1', 'SOCIAL', 'Lesson No.- 1 to 3'),
(5, 5, 'PT-1', 'ART', '1. Shading\n2. Parrot\n3. Pot Design\n4. Scenery'),
(5, 5, 'PT-1', 'COMPUTER', 'Lesson No.- 1'),
(5, 5, 'PT-1', 'G.K.', 'Page No. - 1 to 13'),
(5, 5, 'Half Yearly', 'ENGLISH', 'Lesson No.- 3 to 5\nPoem- The Dark, Courage Courage. Grammar & Writing skills- Refer to the Notebook.'),
(5, 5, 'Half Yearly', 'HINDI', 'पाठ - ३ से ७\nव्याकरण-पाठ १ से ७ पर आधारित व्याकरण और जो व्याकरण कॉपी में करवाया है ।'),
(5, 5, 'Half Yearly', 'MARATHI', 'पाठ क्र.-४ ते ७, व्याकरण - पाठ १ ते ७ पाठावर आधारीत व्याकरण, निबंध'),
(5, 5, 'Half Yearly', 'SANSKRIT', 'पाठ: १ ते: ७. संख्या १ त: ५०,\nव्याकरण - पाठ १ से पाठ ७. इन पाठों पर आधारित व्याकरण'),
(5, 5, 'Half Yearly', 'MATHS', 'Lesson No.- 3 to 7'),
(5, 5, 'Half Yearly', 'SCIENCE', 'Lesson No.- 3 to 8'),
(5, 5, 'Half Yearly', 'SOCIAL', 'Lesson No.- 4 to 10'),
(5, 5, 'Half Yearly', 'ART', '1. 2D Design\n2. Rainy Day\n3. Leaf Printing\n4. Independence Day\n5. Dolphin'),
(5, 5, 'Half Yearly', 'COMPUTER', 'Lesson No.- 2 to 4'),
(5, 5, 'Half Yearly', 'G.K.', 'Page No.- 14 to 34'),
(5, 5, 'PT-2', 'ENGLISH', 'Lesson No.- 1 & 2\nPoems- I Wonder, Lonely as a Cloud.\nGrammar & Writing skills- Refer to the Notebook.'),
(5, 5, 'PT-2', 'HINDI', 'पाठ -८ ,९ और पाठ पर आधारित व्याकरण, जो व्याकरण कॉपी में करवाया है ।'),
(5, 5, 'PT-2', 'MARATHI', 'पाठ क्र. ८ ते १0. पाठावर आधारीत व्याकरण, नाम, सर्वनाम'),
(5, 5, 'PT-2', 'SANSKRIT', 'पाठ: ८, पाठ: ९ च १. संख्या १ ते: ५०, व्याकरण - पाठः १ त: पाठः ९ इन पाठों पर आधारित व्याकरण'),
(5, 5, 'PT-2', 'MATHS', 'Lesson No.- 1 & 2'),
(5, 5, 'PT-2', 'SCIENCE', 'Lesson No.- 1 & 2'),
(5, 5, 'PT-2', 'SOCIAL', 'Lesson No.- 1 to 3'),
(5, 5, 'PT-2', 'ART', '1. Lettering\n2. Ganesh Festival-Memory Drawing\n3. Mozaic Painting'),
(5, 5, 'PT-2', 'COMPUTER', 'Lesson No.- 5 & 6'),
(5, 5, 'PT-2', 'G.K.', 'Page No - 35 to 48'),
(5, 5, 'Annual', 'ENGLISH', 'Lesson No.- 3 to 5\nPoems- Foreign Lands, Abou Ben Adhem.\nGrammar & Writing skills- Refer to the Notebook.'),
(5, 5, 'Annual', 'HINDI', 'पाठ - १० से १४\n८ से १४ पाठ पर आधारित व्याकरण और जो व्याकरण कॉपी में करवाया है ।'),
(5, 5, 'Annual', 'MARATHI', 'पाठ क्र. ११ ते १४. व्याकरण - पाठ ८ ते १४ पाठावर आधारीत व्याकरण, निबंध'),
(5, 5, 'Annual', 'SANSKRIT', 'पाठ: १ ते: १४ , व्याकरण - इन पाठोंपर आधारित व्याकरण संख्या, १ से ५० अंको और अक्षरों मे, चित्रवर्णन.'),
(5, 5, 'Annual', 'MATHS', 'Lesson No.- 3 to 5'),
(5, 5, 'Annual', 'SCIENCE', 'Lesson No.- 3 to 6'),
(5, 5, 'Annual', 'SOCIAL', 'Lesson No.- 4 to 9'),
(5, 5, 'Annual', 'ART', '1. Printing (texture)\n2. Diwali festival,\n3. Madhubani Art\n4. Poster Drawing'),
(5, 5, 'Annual', 'COMPUTER', 'Lesson No.- 7 to 9'),
(5, 5, 'Annual', 'G.K.', 'Page No. - 49 to 65');

-- Grade 6
INSERT INTO `periodic_test_syllabus` (`classesID`, `grade`, `exam`, `subject`, `syllabus`) VALUES
(6, 6, 'PT-1', 'ENGLISH', 'Unit 1- Lesson No.-1 and Poem No.3 Grammar & Writing skills- Refer to the Notebook.'),
(6, 6, 'PT-1', 'HINDI', 'पाठ - १,२ पाठों पर आधारित व्याकरण ।'),
(6, 6, 'PT-1', 'MARATHI', 'व्याकरण - शब्दांच्या जाती\nकाळ.'),
(6, 6, 'PT-1', 'SANSKRIT', 'पाठः १ और पाठः २, और पाठः १ और पाठः २ इन पाठोंपर आधारित व्याकरण.'),
(6, 6, 'PT-1', 'MATHS', 'Lesson No.- 1 & 2'),
(6, 6, 'PT-1', 'SCIENCE', 'Lesson No.- 1 & 2'),
(6, 6, 'PT-1', 'SOCIAL', 'Lesson No.- 1 & 2'),
(6, 6, 'PT-1', 'ART', '1. Strippling\n2. Pencil Shading\n3. Pot design'),
(6, 6, 'PT-1', 'COMPUTER', 'Lesson No.- 1 & 2'),
(6, 6, 'PT-1', 'G.K.', 'Current Affairs'),
(6, 6, 'Half Yearly', 'ENGLISH', 'Unit 1- Lesson No.- 2\nUnit- 3, 4\nGrammar & Writing skills- Refer to the Notebook.'),
(6, 6, 'Half Yearly', 'HINDI', 'पाठ - १ से ६,पाठों पर आधारित व्याकरण , निबंध लेखन, पत्र लेखन, अनुच्छेद ।'),
(6, 6, 'Half Yearly', 'MARATHI', 'पाठ क्र २, ४,५,६,७,८,९\nशब्दांच्या जाती, काळ, निबंध, पत्र, बातमी आकलन, गोष्ट.'),
(6, 6, 'Half Yearly', 'SANSKRIT', 'और पाठः १ से ७ इन पाठोंपर आधारित व्याकरण, संख्या १ से ५0 अंको और अक्षरों मे, शब्दरूपाणि, धातुरूपाणि, चित्रवर्णनम्.'),
(6, 6, 'Half Yearly', 'MATHS', 'Lesson No.- 1 to 6'),
(6, 6, 'Half Yearly', 'SCIENCE', 'Lesson No.- 1 to 6'),
(6, 6, 'Half Yearly', 'SOCIAL', 'Lesson No.- 1 to 7'),
(6, 6, 'Half Yearly', 'ART', '1. Memory Drawing\n2. Poster Drawing - Say No To Plastic\n3. Lettering'),
(6, 6, 'Half Yearly', 'COMPUTER', 'Lesson No.- 3 & 4'),
(6, 6, 'Half Yearly', 'G.K.', 'Current Affairs'),
(6, 6, 'PT-2', 'ENGLISH', 'Unit 5 - full\nGrammar & Writing skills- Refer to the Notebook.'),
(6, 6, 'PT-2', 'HINDI', 'पाठ ७, ८ पाठों पर आधारित व्याकरण ।'),
(6, 6, 'PT-2', 'MARATHI', 'पाठ १०-१५\nशब्दांच्या जाती, काळ\nपाठाखालील व्याकरण.'),
(6, 6, 'PT-2', 'SANSKRIT', 'पाठः ८,९,१० और पाठः१ और पाठः १0 इन पाठोंपर आधारित व्याकरण, संख्या १-५0.'),
(6, 6, 'PT-2', 'MATHS', 'Lesson No.- 7 & 8'),
(6, 6, 'PT-2', 'SCIENCE', 'Lesson No.- 7 & 8'),
(6, 6, 'PT-2', 'SOCIAL', 'Lesson No.- 8 & 9'),
(6, 6, 'PT-2', 'ART', '1. Mozaic Painting\n2. Printing (Texture)\n3. Still Life'),
(6, 6, 'PT-2', 'COMPUTER', 'Lesson No.- 5 & 6'),
(6, 6, 'PT-2', 'G.K.', 'Current Affairs'),
(6, 6, 'Annual', 'ENGLISH', 'Unit 6 &7 - full & (20 % portion from Unit 1 to 5)\nGrammar & Writing skills- Refer to the Notebook.'),
(6, 6, 'Annual', 'HINDI', 'पाठ ७ से १३, पाठों पर आधारित व्याकरण , निबंध, पत्र लेखन ।'),
(6, 6, 'Annual', 'MARATHI', 'पाठ १0-१९, शब्दांच्या जाती काळ पाठाखालील व्याकरण, निबंध, पत्र, जाहिरात,गोष्ट.'),
(6, 6, 'Annual', 'SANSKRIT', 'पाठः ८,९,१0 और पाठः१ से पाठः१५\nइन पाठोंपर आधारित व्याकरण,\nसंख्या १ से ५0 अंको और अक्षरों मे, चित्रवर्णनम्, शब्दरूपाणि, धातुरूपाणि.'),
(6, 6, 'Annual', 'MATHS', 'Lesson No.- 7 to 11'),
(6, 6, 'Annual', 'SCIENCE', 'Lesson No.- 7 to 12'),
(6, 6, 'Annual', 'SOCIAL', 'Lesson No.- 8 to 14'),
(6, 6, 'Annual', 'ART', '1. Diwali Festival\n2. Poster Drawing - Road Safety\n3. Winter Season'),
(6, 6, 'Annual', 'COMPUTER', 'Lesson No.- 7, 8 & 9'),
(6, 6, 'Annual', 'G.K.', 'Current Affairs');

-- Grade 7
INSERT INTO `periodic_test_syllabus` (`classesID`, `grade`, `exam`, `subject`, `syllabus`) VALUES
(7, 7, 'PT-1', 'ENGLISH', '(Unit 1) Lesson No.- 1 and Poem No. 3 Grammar & Writing skills follow the notebook and textbook topics from the book'),
(7, 7, 'PT-1', 'HINDI', 'पाठ: १,२ और इन पाठों पर आधारित व्याकरण'),
(7, 7, 'PT-1', 'MARATHI', 'पाठ: १,२ पाठावर आधारित व्याकरण'),
(7, 7, 'PT-1', 'SANSKRIT', 'पाठ: १,२ और पाठ: १,२ पाठाधारित व्याकरणम्'),
(7, 7, 'PT-1', 'MATHS', 'Lesson No.- 1 & 2'),
(7, 7, 'PT-1', 'SCIENCE', 'Lesson No.- 1 & 2'),
(7, 7, 'PT-1', 'SOCIAL', 'Lesson No.-1 & 2 (Part I)'),
(7, 7, 'PT-1', 'ART', 'Pencil shading\nMy school\nMemory drawing'),
(7, 7, 'PT-1', 'COMPUTER', 'Lesson No.- 1 to 2'),
(7, 7, 'PT-1', 'G.K.', 'Current Affairs'),
(7, 7, 'Half Yearly', 'ENGLISH', 'Unit 1 Lesson No.- 2, Unit 3 & 4 - full, Grammar & Writing skills follow the notebook and textbook topics from the beginning.'),
(7, 7, 'Half Yearly', 'HINDI', 'पाठ: १,२,३,४,५ और इन पाठों पर आधारित व्याकरण, निबंध लेखन, पत्र लेखन, कहानी, नोटिस लेखन'),
(7, 7, 'Half Yearly', 'MARATHI', 'पाठ: २ ते ६ पाठावर आधारित व्याकरण, निबंध, पत्रलेखन, सूचनाफलक'),
(7, 7, 'Half Yearly', 'SANSKRIT', 'पाठ: १ त: ६ और पाठ: १ त: ६ पाठाधारित-व्याकरणम्, उपसर्गा:, प्रत्यया:,समासा:, संख्या: सन्धि:, चित्रवर्णनम्, पत्रलेखनम्'),
(7, 7, 'Half Yearly', 'MATHS', 'Lesson No.- 1 to 7'),
(7, 7, 'Half Yearly', 'SCIENCE', 'Lesson No.- 1 to 6'),
(7, 7, 'Half Yearly', 'SOCIAL', 'Lesson No.- 1 to 10 (Part I)'),
(7, 7, 'Half Yearly', 'ART', 'Mozaic painting\nColour practical\nIndependence Day\nLettering'),
(7, 7, 'Half Yearly', 'COMPUTER', 'Lesson No.- 3 to 5'),
(7, 7, 'Half Yearly', 'G.K.', 'Current Affairs'),
(7, 7, 'PT-2', 'ENGLISH', 'Unit 5, Grammar follow the notebook and textbook'),
(7, 7, 'PT-2', 'HINDI', 'पाठ: ६,७ और इन पाठों पर आधारित व्याकरण'),
(7, 7, 'PT-2', 'MARATHI', 'पाठ: ७ ते १0 पाठावर आधारित व्याकरण'),
(7, 7, 'PT-2', 'SANSKRIT', 'पाठ: ७, ८ पाठ: और १ त: ८ पाठाधारित व्याकरणम्, पत्रलेखनम्'),
(7, 7, 'PT-2', 'MATHS', 'Lesson No.- 8 & 9'),
(7, 7, 'PT-2', 'SCIENCE', 'Lesson No.- 7 & 8'),
(7, 7, 'PT-2', 'SOCIAL', 'Lesson No.- 11 & 12 (Part I) Lesson No.- 1 to 3 (Part II)'),
(7, 7, 'PT-2', 'ART', 'Poster drawing - Environment conservation\nGaneh Festival\nStill Life'),
(7, 7, 'PT-2', 'COMPUTER', 'Lesson No.- 6 & 7'),
(7, 7, 'PT-2', 'G.K.', 'Current Affairs'),
(7, 7, 'Annual', 'ENGLISH', 'Unit 6 &7 - full & (20 % portion from Unit 1 to 5), Grammar & Writing skills follow the notebook and textbook topics from the beginning.'),
(7, 7, 'Annual', 'HINDI', 'पाठ: ६, ७, ८,९, १0 और इन पाठों पर आधारित व्याकरण निबंध लेखन, विज्ञापन, पत्र लेखन, कहानी'),
(7, 7, 'Annual', 'MARATHI', '(20% from Semester- 1) पाठ: ७ ते १४ पाठावर आधारित व्याकरण, कथा, पत्रलेखन, सूचनाफलक / जाहीरात'),
(7, 7, 'Annual', 'SANSKRIT', 'पाठ: ८ त: १२ पाठ: ८ त: १२ और पाठ: १ त: १२ पाठाधारित-व्याकरणम्, उपसर्गा:, प्रत्यया:,समासा:, संख्या: सन्धि:, चित्रवर्णनम्, पत्रलेखनम्'),
(7, 7, 'Annual', 'MATHS', 'Lesson No.- 8 to 14'),
(7, 7, 'Annual', 'SCIENCE', 'Lesson No.- 7 to 12'),
(7, 7, 'Annual', 'SOCIAL', '20% from Semester 1- Lesson No.- 11 & 12 (Part I) Lesson No.- 1 to 8 (Part II)'),
(7, 7, 'Annual', 'ART', 'Leaf printing\nPoster making- Road Safety\nDiwali festival'),
(7, 7, 'Annual', 'COMPUTER', 'Lesson No.- 8 to 10'),
(7, 7, 'Annual', 'G.K.', 'Current Affairs');

-- Grade 8
INSERT INTO `periodic_test_syllabus` (`classesID`, `grade`, `exam`, `subject`, `syllabus`) VALUES
(8, 8, 'PT-1', 'ENGLISH', 'Lesson No.-1 to 5\nGrammar & Writing skills- Refer to the Notebook.'),
(8, 8, 'PT-1', 'HINDI', 'पाठ - १,२\nपाठों पर आधारित व्याकरण'),
(8, 8, 'PT-1', 'MARATHI', 'पाठ २, ३,\nपाठावर आधारीत व्याकरण'),
(8, 8, 'PT-1', 'SANSKRIT', 'पाठ- १, २, और\nपाठाधारित-व्याकरणम्'),
(8, 8, 'PT-1', 'MATHS', 'A Square\nA Cube'),
(8, 8, 'PT-1', 'SCIENCE', 'Lesson No.- 1 & 2'),
(8, 8, 'PT-1', 'SOCIAL', 'Lesson No.- 1 & 2'),
(8, 8, 'PT-1', 'ART', '1. Pencil Shading\n2. 2-D Design'),
(8, 8, 'PT-1', 'COMPUTER', 'Lesson No.- 1 & 2'),
(8, 8, 'PT-1', 'G.K.', 'Current Affairs'),
(8, 8, 'Half Yearly', 'ENGLISH', 'Lesson No.- 1 to 19\nGrammar & Writing skills- Refer to the Notebook.'),
(8, 8, 'Half Yearly', 'HINDI', 'पाठ - १,२,३,४,५\nपाठों पर आधारित व्याकरण\nनिबंध लेखन, पत्र लेखन, कहानी लेखन, नोटिस'),
(8, 8, 'Half Yearly', 'MARATHI', 'पाठ २ ते ७\nपाठावर आधारीत व्याकरण कथा, बातमी, पत्रलेखन'),
(8, 8, 'Half Yearly', 'SANSKRIT', 'पाठ- १ त: ७, और पाठ- १ त: ७\nपाठाधारित-व्याकरणम्, उपसर्गा:, प्रत्यया:, चित्रवर्णनम्, सन्धि:, पत्रलेखनम्, संख्या:'),
(8, 8, 'Half Yearly', 'MATHS', 'Power Play\nQuadrilaterals'),
(8, 8, 'Half Yearly', 'SCIENCE', 'Lesson No.-1 to 7'),
(8, 8, 'Half Yearly', 'SOCIAL', 'Lesson No.-1 to Lesson No.- 7'),
(8, 8, 'Half Yearly', 'ART', '1. Mosaic\n2. Colour Practice\n3. Memory Drawing'),
(8, 8, 'Half Yearly', 'COMPUTER', 'Lesson No.- 3 to 6'),
(8, 8, 'Half Yearly', 'G.K.', 'Current Affairs'),
(8, 8, 'PT-2', 'ENGLISH', 'Lesson No.- 10 to 14\nGrammar & Writing skills- Refer to the Notebook.'),
(8, 8, 'PT-2', 'HINDI', 'पाठ - ६,७\nपाठ पर आधारित व्याकरण'),
(8, 8, 'PT-2', 'MARATHI', 'पाठ ८, ९\nपाठावर आधारीत व्याकरण'),
(8, 8, 'PT-2', 'SANSKRIT', 'पाठ- ८, ९ और पाठ- १ त: ९\nपाठाधारित व्याकरणम्, उपसर्गा:, प्रत्यया:, समासा:,संख्या:, सन्धि:,चित्रवर्णनम्'),
(8, 8, 'PT-2', 'MATHS', 'Number Play\nAlgebraic Expression'),
(8, 8, 'PT-2', 'SCIENCE', 'Lesson No.- 8 & 9'),
(8, 8, 'PT-2', 'ART', '1. Poster Drawing\n2. Still Life\n3. Lettering'),
(8, 8, 'PT-2', 'COMPUTER', 'Lesson No.- 7 & 8'),
(8, 8, 'PT-2', 'G.K.', 'Current Affairs'),
(8, 8, 'Annual', 'ENGLISH', 'Lesson No.- 10 to 21\nGrammar & Writing skills- Refer to the Notebook.'),
(8, 8, 'Annual', 'HINDI', 'पाठ - ६,७,८,९,१0\nपाठों पर आधारित व्याकरण\n(निबंध लेखन, पत्र लेखन, विज्ञापन लेखन, कहानी लेखन, नोटिस)'),
(8, 8, 'Annual', 'MARATHI', 'पाठ ८ ते १३\nपाठावर आधारीत व्याकरण निबंध, पत्रलेखन, बातमी'),
(8, 8, 'Annual', 'SANSKRIT', 'पाठ- ८ त: १३ और पाठ- १ त: १३\nपाठाधारित-व्याकरणम्, उपसर्गा:, प्रत्यया:,समासा:, संख्या: सन्धि:, चित्रवर्णनम्, पत्रलेखनम्'),
(8, 8, 'Annual', 'MATHS', 'Proportional Reasoning - I & II\nSlice of the Pie'),
(8, 8, 'Annual', 'SCIENCE', 'Lesson No.- 8 to 13'),
(8, 8, 'Annual', 'ART', '1. Memory Drawing\n2. 2-D Design\n3. Stippling'),
(8, 8, 'Annual', 'COMPUTER', 'Lesson No.- 9 to 12'),
(8, 8, 'Annual', 'G.K.', 'Current Affairs');

-- ---- Half Yearly timetable: Grades 1-10 ---------------------------------------------
-- Reporting 07:30 am, departure 10:45 am (from the timetable sheet).
DELETE FROM `periodic_test_schedule` WHERE `exam` = 'Half Yearly';

INSERT INTO `periodic_test_schedule` (`classesID`, `grade`, `exam`, `test_date`, `day`, `subject`) VALUES
(1, 1, 'Half Yearly', '2026-09-23', 'WEDNESDAY', 'G.K.'),
(1, 1, 'Half Yearly', '2026-09-24', 'THURSDAY', 'MATHS'),
(1, 1, 'Half Yearly', '2026-09-26', 'SATURDAY', 'ENGLISH'),
(1, 1, 'Half Yearly', '2026-09-28', 'MONDAY', 'EVS'),
(1, 1, 'Half Yearly', '2026-09-29', 'TUESDAY', 'HINDI'),
(1, 1, 'Half Yearly', '2026-09-30', 'WEDNESDAY', 'COMPUTER'),
(1, 1, 'Half Yearly', '2026-10-01', 'THURSDAY', 'MARATHI'),
(1, 1, 'Half Yearly', '2026-10-03', 'SATURDAY', 'ART'),
(2, 2, 'Half Yearly', '2026-09-23', 'WEDNESDAY', 'G.K.'),
(2, 2, 'Half Yearly', '2026-09-24', 'THURSDAY', 'MATHS'),
(2, 2, 'Half Yearly', '2026-09-26', 'SATURDAY', 'ENGLISH'),
(2, 2, 'Half Yearly', '2026-09-28', 'MONDAY', 'EVS'),
(2, 2, 'Half Yearly', '2026-09-29', 'TUESDAY', 'HINDI'),
(2, 2, 'Half Yearly', '2026-09-30', 'WEDNESDAY', 'COMPUTER'),
(2, 2, 'Half Yearly', '2026-10-01', 'THURSDAY', 'MARATHI'),
(2, 2, 'Half Yearly', '2026-10-03', 'SATURDAY', 'ART'),
(3, 3, 'Half Yearly', '2026-09-23', 'WEDNESDAY', 'G.K.'),
(3, 3, 'Half Yearly', '2026-09-24', 'THURSDAY', 'SCIENCE'),
(3, 3, 'Half Yearly', '2026-09-26', 'SATURDAY', 'MATHS'),
(3, 3, 'Half Yearly', '2026-09-28', 'MONDAY', 'ENGLISH'),
(3, 3, 'Half Yearly', '2026-09-29', 'TUESDAY', 'MARATHI'),
(3, 3, 'Half Yearly', '2026-09-30', 'WEDNESDAY', 'ART'),
(3, 3, 'Half Yearly', '2026-10-01', 'THURSDAY', 'HINDI'),
(3, 3, 'Half Yearly', '2026-10-03', 'SATURDAY', 'SOCIAL'),
(3, 3, 'Half Yearly', '2026-10-05', 'MONDAY', 'COMPUTER'),
(4, 4, 'Half Yearly', '2026-09-23', 'WEDNESDAY', 'G.K. / ART'),
(4, 4, 'Half Yearly', '2026-09-24', 'THURSDAY', 'MATHS'),
(4, 4, 'Half Yearly', '2026-09-26', 'SATURDAY', 'SCIENCE'),
(4, 4, 'Half Yearly', '2026-09-28', 'MONDAY', 'SOCIAL'),
(4, 4, 'Half Yearly', '2026-09-29', 'TUESDAY', 'SANSKRIT'),
(4, 4, 'Half Yearly', '2026-09-30', 'WEDNESDAY', 'COMPUTER'),
(4, 4, 'Half Yearly', '2026-10-01', 'THURSDAY', 'HINDI'),
(4, 4, 'Half Yearly', '2026-10-03', 'SATURDAY', 'ENGLISH'),
(4, 4, 'Half Yearly', '2026-10-05', 'MONDAY', 'MARATHI'),
(5, 5, 'Half Yearly', '2026-09-23', 'WEDNESDAY', 'G.K. / ART'),
(5, 5, 'Half Yearly', '2026-09-24', 'THURSDAY', 'MATHS'),
(5, 5, 'Half Yearly', '2026-09-26', 'SATURDAY', 'SCIENCE'),
(5, 5, 'Half Yearly', '2026-09-28', 'MONDAY', 'SOCIAL'),
(5, 5, 'Half Yearly', '2026-09-29', 'TUESDAY', 'SANSKRIT'),
(5, 5, 'Half Yearly', '2026-09-30', 'WEDNESDAY', 'COMPUTER'),
(5, 5, 'Half Yearly', '2026-10-01', 'THURSDAY', 'HINDI'),
(5, 5, 'Half Yearly', '2026-10-03', 'SATURDAY', 'ENGLISH'),
(5, 5, 'Half Yearly', '2026-10-05', 'MONDAY', 'MARATHI'),
(6, 6, 'Half Yearly', '2026-09-23', 'WEDNESDAY', 'G.K. / ART'),
(6, 6, 'Half Yearly', '2026-09-24', 'THURSDAY', 'SOCIAL'),
(6, 6, 'Half Yearly', '2026-09-26', 'SATURDAY', 'MATHS'),
(6, 6, 'Half Yearly', '2026-09-28', 'MONDAY', 'MARATHI'),
(6, 6, 'Half Yearly', '2026-09-29', 'TUESDAY', 'COMPUTER'),
(6, 6, 'Half Yearly', '2026-09-30', 'WEDNESDAY', 'HINDI'),
(6, 6, 'Half Yearly', '2026-10-01', 'THURSDAY', 'SANSKRIT'),
(6, 6, 'Half Yearly', '2026-10-03', 'SATURDAY', 'ENGLISH'),
(6, 6, 'Half Yearly', '2026-10-05', 'MONDAY', 'SCIENCE'),
(7, 7, 'Half Yearly', '2026-09-23', 'WEDNESDAY', 'G.K. / ART'),
(7, 7, 'Half Yearly', '2026-09-24', 'THURSDAY', 'SCIENCE'),
(7, 7, 'Half Yearly', '2026-09-26', 'SATURDAY', 'ENGLISH'),
(7, 7, 'Half Yearly', '2026-09-28', 'MONDAY', 'SOCIAL'),
(7, 7, 'Half Yearly', '2026-09-29', 'TUESDAY', 'COMPUTER'),
(7, 7, 'Half Yearly', '2026-09-30', 'WEDNESDAY', 'MARATHI'),
(7, 7, 'Half Yearly', '2026-10-01', 'THURSDAY', 'HINDI'),
(7, 7, 'Half Yearly', '2026-10-03', 'SATURDAY', 'MATHS'),
(7, 7, 'Half Yearly', '2026-10-05', 'MONDAY', 'SANSKRIT'),
(8, 8, 'Half Yearly', '2026-09-23', 'WEDNESDAY', 'G.K. / ART'),
(8, 8, 'Half Yearly', '2026-09-24', 'THURSDAY', 'ENGLISH'),
(8, 8, 'Half Yearly', '2026-09-26', 'SATURDAY', 'SOCIAL'),
(8, 8, 'Half Yearly', '2026-09-28', 'MONDAY', 'MATHS'),
(8, 8, 'Half Yearly', '2026-09-29', 'TUESDAY', 'SANSKRIT'),
(8, 8, 'Half Yearly', '2026-09-30', 'WEDNESDAY', 'COMPUTER'),
(8, 8, 'Half Yearly', '2026-10-01', 'THURSDAY', 'HINDI'),
(8, 8, 'Half Yearly', '2026-10-03', 'SATURDAY', 'MARATHI'),
(8, 8, 'Half Yearly', '2026-10-05', 'MONDAY', 'SCIENCE'),
(9, 9, 'Half Yearly', '2026-09-23', 'WEDNESDAY', 'HINDI'),
(9, 9, 'Half Yearly', '2026-09-24', 'THURSDAY', 'I.T.'),
(9, 9, 'Half Yearly', '2026-09-26', 'SATURDAY', 'ENGLISH'),
(9, 9, 'Half Yearly', '2026-09-28', 'MONDAY', 'MATHS'),
(9, 9, 'Half Yearly', '2026-09-30', 'WEDNESDAY', 'SOCIAL'),
(9, 9, 'Half Yearly', '2026-10-03', 'SATURDAY', 'SCIENCE'),
(9, 9, 'Half Yearly', '2026-10-05', 'MONDAY', 'MARATHI'),
(10, 10, 'Half Yearly', '2026-09-23', 'WEDNESDAY', 'HINDI / SANSKRIT'),
(10, 10, 'Half Yearly', '2026-09-24', 'THURSDAY', 'I.T.'),
(10, 10, 'Half Yearly', '2026-09-26', 'SATURDAY', 'ENGLISH'),
(10, 10, 'Half Yearly', '2026-09-28', 'MONDAY', 'MATHS'),
(10, 10, 'Half Yearly', '2026-09-30', 'WEDNESDAY', 'SOCIAL'),
(10, 10, 'Half Yearly', '2026-10-03', 'SATURDAY', 'SCIENCE'),
(10, 10, 'Half Yearly', '2026-10-05', 'MONDAY', 'MARATHI');
